import { StyleCategory, StyleDistribution } from './types';

export const INITIAL_STYLES: StyleCategory[] = [
  {
    id: 'user',
    name: "Style Utilisateur Principal",
    description: "La 'voix' de base de l'auteur, souvent un mélange de professionnalisme et de clarté.",
    documents: [
      { id: 'user1', name: 'email_professionnel_long.txt', content: "Bonjour à toute l'équipe,\n\nSuite à notre réunion de planification de lundi dernier, je tenais à vous faire parvenir un compte-rendu détaillé des points abordés et des décisions prises concernant le projet 'Phoenix'. Premièrement, nous avons validé le calendrier de développement pour le T3, avec une attention particulière portée aux jalons critiques des semaines 5 et 8. Il est impératif que chaque département respecte ces échéances pour éviter un effet domino sur la livraison finale. J'ai joint le diagramme de Gantt mis à jour à cet effet.\n\nDeuxièmement, concernant l'allocation budgétaire, nous avons convenu d'une réaffectation de 15% du budget marketing vers le pôle R&D pour accélérer le prototypage de la nouvelle interface. C'était une décision difficile, mais nécessaire pour garantir la compétitivité du produit. Sarah, pourriez-vous s'il vous plaît préparer une ventilation révisée pour la fin de la semaine ?\n\nEnfin, un point qui me semble crucial : la communication inter-équipes. Nous avons noté quelques frictions et pertes d'information entre les équipes de développement et de design. Pour y remédier, nous allons mettre en place un stand-up meeting quotidien de 15 minutes à 9h30. L'objectif n'est pas de micro-manager, mais bien de fluidifier les échanges et de s'assurer que tout le monde est sur la même longueur d'onde. En d'autres termes, ce que j'essaie de dire, c'est que nous devons être plus proactifs pour éviter les silos. C'est vraiment la clé.\n\nJe suis convaincu que ces ajustements nous mettront sur la bonne voie pour un lancement réussi. N'hésitez pas à revenir vers moi si vous avez des questions ou des préoccupations. Je reste à votre entière disposition.\n\nCordialement,\nMarc." },
      { id: 'user2', name: 'rapport_analyse_detaille.txt', content: "Le présent rapport a pour objectif d'analyser en profondeur les tendances émergentes sur le marché des solutions SaaS B2B pour le premier semestre 2024. La méthodologie employée repose sur une approche mixte, combinant une analyse quantitative des données collectées auprès de 500 entreprises du secteur, ainsi qu'une série d'entretiens qualitatifs menés avec 25 DSI et responsables de l'innovation.\n\nLes résultats préliminaires indiquent une croissance significative, de l'ordre de 22%, du segment des plateformes d'automatisation 'low-code'. Cette tendance est principalement portée par une demande accrue des PME cherchant à optimiser leurs processus internes sans investir dans des équipes de développement spécialisées. On observe cependant une saturation naissante sur le marché des CRM généralistes, avec une fragmentation de l'offre et une pression sur les prix. Il semble que les acteurs qui tirent leur épingle du jeu sont ceux qui proposent des solutions de niche, ultra-spécialisées par secteur d'activité.\n\nUn autre point saillant de notre analyse est l'importance croissante de la sécurité des données et de la conformité au RGPD comme critère de décision majeur. Les entreprises ne recherchent plus seulement une solution fonctionnelle ; elles exigent des garanties robustes en matière de protection de leurs informations sensibles. Bref, la sécurité n'est plus une option, c'est un prérequis non négociable. Nous recommandons donc aux acteurs du secteur de faire de cet aspect un axe de communication central." },
      { id: 'user3', name: 'memo_projet_interne.txt', content: "Note à tous les contributeurs du projet 'Titan',\n\nCeci est un mémo rapide pour vous tenir informés de l'avancement et des prochaines étapes. Nous avons officiellement complété la phase de conception et les premiers retours du groupe de test sont extrêmement positifs. Un grand bravo à l'équipe UX/UI pour son travail remarquable sur les maquettes interactives. Vraiment, le résultat est bluffant.\n\nNous entrons maintenant dans la phase de développement alpha. Le backlog a été priorisé dans Jira, et chaque développeur devrait avoir ses tâches assignées pour les deux prochains sprints. Je vous demande de porter une attention particulière à la documentation de votre code. C'est peut-être un peu rébarbatif, mais cela nous fera gagner un temps précieux lors de la phase de débogage et de maintenance. Pensez à nos futurs nous !\n\nUn petit rappel logistique : les vendredis sont désormais des 'focus days', sans réunions internes, pour permettre à chacun de se concentrer sur des tâches de fond. Essayons tous de respecter cette règle pour maximiser notre productivité collective. Si une urgence absolue survient, merci de passer par les canaux Slack dédiés plutôt que d'interrompre directement un collègue.\n\nL'objectif est de présenter une version alpha fonctionnelle à la direction d'ici le 15 du mois prochain. C'est un défi, mais je suis persuadé que nous avons le talent et la motivation pour y arriver. Continuons sur cette belle lancée.\n\nMerci à tous pour votre engagement." }
    ],
    keywords: ['clair', 'concis', 'direct', 'professionnel', 'structuré']
  },
  {
    id: 'journalistic',
    name: "Style Journalistique",
    description: "Clarté, objectivité et narration factuelle, souvent avec une accroche percutante.",
    documents: [
      { id: 'jour1', name: 'article_enquete_long.txt', content: "Hier, dans un revirement inattendu, les autorités de régulation du numérique ont annoncé une nouvelle série de mesures drastiques visant à encadrer l'utilisation des algorithmes de recommandation par les géants de la tech. Cette décision, qui prendra effet dès le mois prochain, pourrait bien rebattre les cartes d'un secteur jusqu'ici habitué à une quasi-autorégulation.\n\nAu cœur du dispositif, l'obligation pour les plateformes de plus de 10 millions d'utilisateurs de proposer une alternative à leur flux de contenu algorithmique, une option 'chronologique' simple. 'Le citoyen doit pouvoir reprendre le contrôle de ce qu'il voit', a martelé le ministre du Numérique lors d'une conférence de presse tendue. 'Nous ne pouvons plus laisser des boîtes noires dicter le débat public.'\n\nDes experts s'interrogent déjà sur l'impact potentiel de ces régulations sur l'innovation. Pour Julien Meyer, analyste chez Tech-Insight, 'c'est une intervention nécessaire, mais qui risque de freiner la recherche en personnalisation et en intelligence artificielle'. Il pointe notamment le risque de voir les plus petites plateformes, moins armées juridiquement, pénalisées face aux GAFAM. La question est donc de savoir si cette mesure atteindra sa cible sans faire de dégâts collatéraux. Du côté des associations de consommateurs, on salue une 'avancée historique pour la transparence'. Reste à voir comment les entreprises concernées, pour l'instant silencieuses, réagiront à ce qui s'apparente à un véritable tour de vis réglementaire." },
      { id: 'jour2', name: 'reportage_terrain.txt', content: "Le soleil tape fort sur les toits en tôle de la 'Silicon Savannah', le surnom donné au quartier de Nairobi où fleurissent les startups technologiques. Ici, loin des clichés misérabilistes, une jeunesse surdiplômée et hyper-connectée invente l'Afrique de demain. L'énergie est palpable. Dans les espaces de coworking qui essaiment à chaque coin de rue, on parle 'fintech', 'agritech' et 'blockchain' avec un accent kenyan.\n\nNous rencontrons Brenda, 28 ans, co-fondatrice d'une application qui permet aux petits agriculteurs de suivre les cours du marché en temps réel via un simple SMS. 'L'idée est née d'un problème concret', explique-t-elle entre deux appels. 'Mon grand-père se faisait systématiquement avoir par les intermédiaires. La technologie, pour nous, ce n'est pas un gadget, c'est un outil d'émancipation.' Son histoire n'est pas isolée. Des centaines de jeunes entrepreneurs comme elle tentent de résoudre des problèmes locaux avec des solutions globales. L'écosystème est soutenu par des incubateurs locaux et des investisseurs étrangers qui ont flairé le potentiel de ce marché de plus d'un milliard de consommateurs. Bien sûr, tout n'est pas rose. Les coupures d'électricité sont fréquentes et l'accès au financement reste un parcours du combattant. Mais la détermination, elle, est sans faille. 'On n'attend pas que les solutions viennent d'ailleurs', conclut Brenda avec un sourire. 'On les construit nous-mêmes.'" },
    ],
    keywords: ['factuel', 'informatif', 'engageant', 'narratif', 'objectif']
  },
  {
    id: 'academic',
    name: "Style Académique",
    description: "Rigueur, précision, argumentation formelle et citations.",
    documents: [
      { id: 'acad1', name: 'these_recherche_long.txt', content: "Cette recherche postule que les structures cognitives préexistantes, façonnées par l'expérience et l'éducation, influencent de manière substantielle les processus décisionnels en situation d'incertitude. En nous appuyant sur les travaux fondateurs de Kahneman et Tversky (1979) concernant la théorie des perspectives, ainsi que sur les développements plus récents en neuroéconomie (Glimcher & Fehr, 2013), nous avons élaboré un modèle expérimental visant à tester cette hypothèse centrale. Notre protocole se distingue des recherches antérieures par l'introduction d'une variable de 'charge cognitive', mesurée par des tâches interférentes, afin d'évaluer son impact sur le recours aux heuristiques de jugement.\n\nL'échantillon, composé de 120 participants, a été soumis à une série de dilemmes financiers à l'issue probabiliste. Les résultats, analysés via une régression logistique multivariée, indiquent une corrélation statistiquement significative (p < 0.01) entre une charge cognitive élevée et une augmentation de l'aversion à la perte, un biais cognitif bien documenté. Cette observation suggère que l'épuisement des ressources attentionnelles limite la capacité de l'individu à s'engager dans un traitement délibératif et analytique, favorisant ainsi des réponses plus intuitives et systémiques. En conséquence, nos conclusions remettent en question le postulat de rationalité pure de l'acteur économique, particulièrement dans des contextes informationnels denses ou temporellement contraints. Ces travaux ouvrent des perspectives pour l'optimisation des interfaces homme-machine dans des domaines critiques tels que la finance de marché ou le diagnostic médical." },
      { id: 'acad2', name: 'abstract_conference.txt', content: "L'avènement des grands modèles de langage (LLM) a initié un changement de paradigme dans le domaine du traitement automatique du langage naturel (NLP). Cependant, leur propension à générer des informations factuellement incorrectes, un phénomène connu sous le nom d' 'hallucination' (Ji et al., 2023), constitue un obstacle majeur à leur déploiement dans des applications à haute fiabilité. Cet article propose une nouvelle architecture, nommée 'Fact-Checker Fusion' (FCF), qui intègre un mécanisme de vérification des faits en temps réel au sein même du processus génératif. Contrairement aux approches de post-traitement qui vérifient le texte une fois généré, FCF utilise un réseau attentionnel croisé pour interroger continuellement une base de connaissances structurée (e.g., Wikidata) à chaque étape de décodage. Ce faisant, le modèle est capable d'ajuster la probabilité des jetons candidats en fonction de leur cohérence factuelle. Nous avons évalué notre approche sur un benchmark de questions-réponses factuelles et démontré une réduction de 73% du taux d'hallucination par rapport à un modèle de base de type LLaMA-2, avec une augmentation négligeable de la latence inférentielle. Nos résultats suggèrent que l'intégration de contraintes externes durant la génération est une voie prometteuse pour améliorer la fiabilité des LLMs." }
    ],
    keywords: ['formel', 'analytique', 'sourcé', 'précis', 'argumenté']
  },
  {
    id: 'conversational',
    name: "Style Conversationnel",
    description: "Proximité, ton direct, langage accessible et questions au lecteur.",
    documents: [
      { id: 'conv1', name: 'post_de_blog_long.txt', content: "Vous vous êtes déjà demandé pourquoi certaines habitudes, comme arrêter de scroller sur Instagram à minuit, sont si incroyablement difficiles à changer ? On a tous été là. On se dit 'demain, j'arrête', et le lendemain, on y est encore. Frustrant, non ?\n\nEn fait, c'est assez simple quand on y pense. Notre cerveau, ce super-ordinateur un peu paresseux, est câblé pour préférer les chemins familiers. C'est ce qu'on appelle l'économie cognitive. Chaque fois que vous répétez une action, vous creusez une sorte d'autoroute neuronale. Essayer de faire quelque chose de nouveau, c'est comme devoir défricher un sentier en pleine jungle avec une machette. Pas étonnant qu'on préfère l'autoroute !\n\nAlors, comment on peut déjouer ce système ? Le truc, c'est de ne pas essayer de bloquer l'autoroute, mais plutôt de construire une nouvelle bretelle de sortie, plus attrayante. Vous voulez arrêter de scroller ? Ne vous contentez pas de poser le téléphone. Remplacez cette habitude par une autre, plus positive. Par exemple, mettez un livre que vous avez envie de lire sur votre table de chevet. L'idée, c'est de rendre la nouvelle habitude plus facile et plus gratifiante que l'ancienne. Au début, ça demande un effort conscient, c'est sûr. Mais petit à petit, votre nouvelle bretelle de sortie va se transformer en une nouvelle autoroute. Et l'ancienne ? Elle finira par être envahie par les herbes folles. Plutôt cool comme image, non ? Essayez ce soir, vous m'en direz des nouvelles !" },
      { id: 'conv2', name: 'tutoriel_amical.txt', content: "Ok, alors aujourd'hui, on va s'attaquer à un monstre : la mise en page en CSS. Je sais, je sais, rien que le mot 'CSS' peut donner des sueurs froides. On a tous passé des heures à essayer de centrer une div, pour finalement tout casser. Mais respirez, ça va bien se passer.\n\nLe secret, vraiment, c'est de ne plus utiliser les vieilles méthodes comme les `float`. Oubliez ça. C'est dépassé et ça va juste vous compliquer la vie. Le duo magique aujourd'hui, c'est Flexbox et Grid. Pensez à Flexbox comme à un expert pour aligner des choses sur une seule ligne (ou une seule colonne). C'est parfait pour les barres de navigation, les listes d'items, ce genre de choses. C'est super simple : sur le conteneur parent, vous mettez `display: flex;` et hop, la magie opère. Après, vous pouvez jouer avec `justify-content` pour l'alignement horizontal et `align-items` pour le vertical. Un vrai jeu d'enfant, une fois qu'on a compris le principe.\n\nGrid, c'est le grand frère de Flexbox. Lui, il pense en deux dimensions : lignes ET colonnes. C'est l'outil ultime pour la mise en page globale de votre site. Vous voulez une barre latérale, un contenu principal et un pied de page ? Avec `display: grid;` et quelques `grid-template-columns`, c'est réglé en trois lignes de code. Sérieusement. Fini les calculs de pourcentages et les marges négatives bizarres. Alors, mon conseil : arrêtez de vous battre avec les vieilles techniques. Passez 30 minutes à regarder un tuto sur Flexbox, et je vous promets que votre vie de développeur va changer. On commence ?" },
    ],
    keywords: ['accessible', 'relatable', 'informel', 'direct', 'engageant']
  },
  {
    id: 'creative',
    name: "Style Créatif",
    description: "Originalité, imagerie, langage évocateur et expression personnelle.",
    documents: [
      { id: 'crea1', name: 'nouvelle_fiction_long.txt', content: "La lune, tel un disque d'argent usé, déversait une lumière blafarde sur les toits endormis de la ville basse. C'était une clarté fantomatique, une peinture au lait qui rendait les ombres longues et inquiétantes. Le silence n'était brisé que par le murmure du vent dans les ruelles désertes, un secret chuchoté à la nuit, une complainte que seules les gargouilles de pierre semblaient comprendre. C'est dans ce genre de nuit que les souvenirs remontent, non pas comme des images claires, mais comme des parfums, des sensations. L'odeur de la pluie sur le bitume chaud, le grain d'un vieux livre sous les doigts, le goût métallique de la peur au fond de la gorge.\n\nIl marchait sans but, les mains dans les poches de son manteau trop grand, un vaisseau fantôme dans un océan de pavés. Chaque lampadaire était un phare solitaire, découpant des îlots de lumière orangée dans les ténèbres. Il se sentait exactement comme ça : un îlot. Isolé, cerné par une mer d'incompréhension. Les fenêtres des immeubles étaient des yeux clos, indifférents à sa dérive. Derrière, des vies se déroulaient, des rêves s'effilochaient, des amours naissaient et mouraient. Des mondes entiers, si proches et pourtant inaccessibles. Il leva les yeux vers la lune, ce témoin muet et éternel. Et pour la première fois de la nuit, il ne se sentit pas tout à fait seul. Il y avait elle, et lui. Deux solitudes qui se faisaient face à des millions de kilomètres de distance." },
      { id: 'crea2', name: 'description_poetique.txt', content: "La forêt d'automne n'était pas triste, elle était en feu. Un incendie silencieux, un brasier d'or, de cuivre et de pourpre qui consumait lentement l'été. Chaque feuille était une étincelle, une dernière protestation flamboyante avant la chute. Le vent, en passant dans les branches, ne faisait pas de bruit ; il jouait une musique, une partition écrite avec des frôlements et des craquements, une mélodie que seuls les arbres pouvaient déchiffrer. L'air sentait la terre humide, le champignon et la promesse de la pluie. C'était une odeur de fin et de commencement, le parfum du cycle immuable des choses. Marcher sur le tapis de feuilles mortes, c'était comme marcher sur des années de souvenirs, chaque pas faisant craquer une saison passée. Il y avait dans cette décomposition une beauté étrange, une sorte de paix. La nature ne mourait pas, elle se préparait simplement à dormir, à rêver de printemps sous une couverture de givre. Et dans ce grand sommeil annoncé, tout semblait enfin à sa juste place. Il n'y avait rien à ajouter, rien à retirer. Juste à être là, et à respirer." },
    ],
    keywords: ['imaginatif', 'évocateur', 'artistique', 'sensoriel', 'métaphorique']
  },
];

export const INITIAL_DISTRIBUTION: StyleDistribution = {
  user: 45,
  journalistic: 20,
  academic: 15,
  conversational: 12,
  creative: 8,
};

export const MAX_INPUT_CHARS = 500000;
